# Change these first
owner: luke-beep # Your GitHub organization or username, where this repository lives
repo: status.lukehjo.dev # The name of this repository

sites:
  - name: LukeHjo's Dev Log
    url: https://tech.lukehjo.dev
  - name: Personal Site
    url: https://lukehjo.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lukehjo.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: lukehjo.dev
  introTitle: "**lukehjo.dev** status page."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: LukeHjo's Dev Log
      href: https://tech.lukehjo.dev
    - title: Personal Site
      href: https://lukehjo.dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
